-- ============================================================================
-- Wellspire SMS — Student learning: CBSE syllabus, study material & tests
-- Migration 0007. Idempotent (IF NOT EXISTS / ON CONFLICT DO NOTHING).
-- ============================================================================

create table if not exists syllabus (
  id text primary key,
  school_id uuid references schools(id) on delete cascade,
  grade text not null, subject text not null, chapter_no int not null,
  title text not null, topics text[] default '{}', term text, board text default 'CBSE',
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists study_materials (
  id text primary key,
  school_id uuid references schools(id) on delete cascade,
  grade text not null, subject text not null, title text not null,
  type text not null, description text, url text, minutes int,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists quizzes (
  id text primary key,
  school_id uuid references schools(id) on delete cascade,
  grade text not null, subject text not null, title text not null,
  description text, difficulty text, duration_sec int, question_count int, total_marks int,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists quiz_questions (
  id text primary key,
  quiz_id text references quizzes(id) on delete cascade,
  seq int not null, prompt text not null, options text[] not null,
  correct_index int not null, explanation text, marks int default 1
);
create table if not exists quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  quiz_id text references quizzes(id) on delete cascade,
  school_id uuid references schools(id) on delete cascade,
  student_id text, student_name text,
  score int, total int, percent int, badge text, duration_sec int,
  taken_at timestamptz default now()
);

alter table syllabus enable row level security;
alter table study_materials enable row level security;
alter table quizzes enable row level security;
alter table quiz_questions enable row level security;
alter table quiz_attempts enable row level security;
do $$ begin
  perform 1;
  begin create policy p_read on syllabus for select to authenticated using (true); exception when duplicate_object then null; end;
  begin create policy p_read on study_materials for select to authenticated using (true); exception when duplicate_object then null; end;
  begin create policy p_read on quizzes for select to authenticated using (true); exception when duplicate_object then null; end;
  begin create policy p_read on quiz_questions for select to authenticated using (true); exception when duplicate_object then null; end;
  begin create policy p_rw on quiz_attempts for all to authenticated using (true) with check (true); exception when duplicate_object then null; end;
end $$;

-- Seed --------------------------------------------------------------------
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-1','11111111-1111-1111-1111-111111111111','5','Mathematics',1,'The Fish Tale',ARRAY['Large numbers','Multiplication in daily life','Estimation']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-2','11111111-1111-1111-1111-111111111111','5','Mathematics',2,'Shapes and Angles',ARRAY['Types of angles','Comparing angles','Angles in shapes']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-3','11111111-1111-1111-1111-111111111111','5','Mathematics',3,'How Many Squares?',ARRAY['Area by counting squares','Perimeter','Comparing areas']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-4','11111111-1111-1111-1111-111111111111','5','Mathematics',4,'Parts and Wholes',ARRAY['Fractions of a whole','Equivalent fractions','Fractions in daily life']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-5','11111111-1111-1111-1111-111111111111','5','Mathematics',5,'Does it Look the Same?',ARRAY['Symmetry','Rotations','Patterns']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-6','11111111-1111-1111-1111-111111111111','5','Mathematics',6,'Be My Multiple, I''ll be Your Factor',ARRAY['Factors','Multiples','Common factors & multiples']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-mathematics-10','11111111-1111-1111-1111-111111111111','5','Mathematics',10,'Tenths and Hundredths',ARRAY['Decimals','Place value','Money & measurement']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-evs-1','11111111-1111-1111-1111-111111111111','5','EVS',1,'Super Senses',ARRAY['Animal senses','Observation','Adaptation']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-evs-6','11111111-1111-1111-1111-111111111111','5','EVS',6,'Every Drop Counts',ARRAY['Sources of water','Water scarcity','Rainwater harvesting']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-5-evs-11','11111111-1111-1111-1111-111111111111','5','EVS',11,'Sunita in Space',ARRAY['Gravity','Earth from space','Astronauts']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-1','11111111-1111-1111-1111-111111111111','6','Mathematics',1,'Knowing Our Numbers',ARRAY['Comparing numbers','Large numbers','Estimation','Roman numerals']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-2','11111111-1111-1111-1111-111111111111','6','Mathematics',2,'Whole Numbers',ARRAY['Number line','Properties','Patterns']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-3','11111111-1111-1111-1111-111111111111','6','Mathematics',3,'Playing with Numbers',ARRAY['Factors & multiples','Prime & composite','Divisibility','HCF & LCM']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-6','11111111-1111-1111-1111-111111111111','6','Mathematics',6,'Integers',ARRAY['Positive & negative','Number line','Addition & subtraction']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-7','11111111-1111-1111-1111-111111111111','6','Mathematics',7,'Fractions',ARRAY['Types of fractions','Equivalent fractions','Operations']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-8','11111111-1111-1111-1111-111111111111','6','Mathematics',8,'Decimals',ARRAY['Place value','Comparing decimals','Addition & subtraction']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-11','11111111-1111-1111-1111-111111111111','6','Mathematics',11,'Algebra',ARRAY['Variables','Expressions','Simple equations']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-mathematics-12','11111111-1111-1111-1111-111111111111','6','Mathematics',12,'Ratio and Proportion',ARRAY['Ratio','Proportion','Unitary method']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-1','11111111-1111-1111-1111-111111111111','6','Science',1,'Food: Where Does It Come From?',ARRAY['Food sources','Plant & animal products','Ingredients']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-2','11111111-1111-1111-1111-111111111111','6','Science',2,'Components of Food',ARRAY['Nutrients','Balanced diet','Deficiency diseases']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-3','11111111-1111-1111-1111-111111111111','6','Science',3,'Fibre to Fabric',ARRAY['Natural fibres','Cotton & jute','Spinning & weaving']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-4','11111111-1111-1111-1111-111111111111','6','Science',4,'Sorting Materials into Groups',ARRAY['Properties of materials','Solubility','Transparency']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-10','11111111-1111-1111-1111-111111111111','6','Science',10,'Motion and Measurement of Distances',ARRAY['Standard units','Types of motion','Measurement']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-11','11111111-1111-1111-1111-111111111111','6','Science',11,'Light, Shadows and Reflections',ARRAY['Luminous objects','Shadows','Pinhole camera','Mirrors']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-12','11111111-1111-1111-1111-111111111111','6','Science',12,'Electricity and Circuits',ARRAY['Electric cell','Circuits','Conductors & insulators']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-science-13','11111111-1111-1111-1111-111111111111','6','Science',13,'Fun with Magnets',ARRAY['Magnetic materials','Poles','Compass']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-socialscience-1','11111111-1111-1111-1111-111111111111','6','Social Science',1,'What, Where, How and When? (History)',ARRAY['Sources of history','Manuscripts','Archaeology']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-socialscience-2','11111111-1111-1111-1111-111111111111','6','Social Science',2,'The Earth in the Solar System (Geography)',ARRAY['Planets','Stars','The Moon']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-socialscience-3','11111111-1111-1111-1111-111111111111','6','Social Science',3,'Globe: Latitudes and Longitudes (Geography)',ARRAY['Latitudes','Longitudes','Time zones']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-socialscience-4','11111111-1111-1111-1111-111111111111','6','Social Science',4,'Understanding Diversity (Civics)',ARRAY['Diversity in India','Unity in diversity','Prejudice']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-english-1','11111111-1111-1111-1111-111111111111','6','English',1,'Who Did Patrick’s Homework?',ARRAY['Reading comprehension','New words','Grammar: nouns']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-6-english-2','11111111-1111-1111-1111-111111111111','6','English',2,'How the Dog Found Himself a New Master!',ARRAY['Comprehension','Adjectives','Story values']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-science-1','11111111-1111-1111-1111-111111111111','7','Science',1,'Nutrition in Plants',ARRAY['Photosynthesis','Autotrophs & heterotrophs','Parasites']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-science-2','11111111-1111-1111-1111-111111111111','7','Science',2,'Nutrition in Animals',ARRAY['Digestive system','Nutrition in humans','Ruminants']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-science-4','11111111-1111-1111-1111-111111111111','7','Science',4,'Heat',ARRAY['Temperature','Thermometers','Conduction & convection']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-science-5','11111111-1111-1111-1111-111111111111','7','Science',5,'Acids, Bases and Salts',ARRAY['Indicators','Neutralisation','Everyday examples']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-mathematics-1','11111111-1111-1111-1111-111111111111','7','Mathematics',1,'Integers',ARRAY['Properties','Multiplication & division','Number line']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-mathematics-2','11111111-1111-1111-1111-111111111111','7','Mathematics',2,'Fractions and Decimals',ARRAY['Operations','Word problems','Conversions']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-7-mathematics-6','11111111-1111-1111-1111-111111111111','7','Mathematics',6,'The Triangle and its Properties',ARRAY['Medians & altitudes','Angle sum','Pythagoras']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-8-science-1','11111111-1111-1111-1111-111111111111','8','Science',1,'Crop Production and Management',ARRAY['Agricultural practices','Irrigation','Crop protection']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-8-science-3','11111111-1111-1111-1111-111111111111','8','Science',3,'Coal and Petroleum',ARRAY['Natural resources','Fossil fuels','Conservation']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-8-science-11','11111111-1111-1111-1111-111111111111','8','Science',11,'Force and Pressure',ARRAY['Types of forces','Pressure','Atmospheric pressure']::text[],'Term 2','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-8-mathematics-1','11111111-1111-1111-1111-111111111111','8','Mathematics',1,'Rational Numbers',ARRAY['Properties','Representation','Operations']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-8-mathematics-2','11111111-1111-1111-1111-111111111111','8','Mathematics',2,'Linear Equations in One Variable',ARRAY['Solving equations','Word problems','Applications']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into syllabus (id,school_id,grade,subject,chapter_no,title,topics,term,board) values ('syl-8-mathematics-6','11111111-1111-1111-1111-111111111111','8','Mathematics',6,'Squares and Square Roots',ARRAY['Perfect squares','Finding square roots','Estimation']::text[],'Term 1','CBSE') on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-1','11111111-1111-1111-1111-111111111111','6','Science','Components of Food — Revision Notes','notes','Nutrients, balanced diet, and deficiency diseases summarised for quick revision.','https://ncert.nic.in/textbook.php',12) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-2','11111111-1111-1111-1111-111111111111','6','Science','Balanced Diet — Concept Video','video','Animated explainer on carbohydrates, proteins, fats, vitamins and minerals.','https://www.youtube.com/results?search_query=components+of+food+class+6',8) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-3','11111111-1111-1111-1111-111111111111','6','Science','Light & Shadows — Worksheet','worksheet','15 practice questions on luminous objects, shadows and reflection.','https://ncert.nic.in/textbook.php',20) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-4','11111111-1111-1111-1111-111111111111','6','Mathematics','Integers — Revision Notes','notes','Number line, addition and subtraction of integers with worked examples.','https://ncert.nic.in/textbook.php',10) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-5','11111111-1111-1111-1111-111111111111','6','Mathematics','Fractions — Practice Sheet','worksheet','Mixed practice: equivalent fractions, comparison and operations.','https://ncert.nic.in/textbook.php',25) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-6','11111111-1111-1111-1111-111111111111','6','Social Science','Latitudes & Longitudes — Notes','notes','Understand the globe, important lines and how time zones work.','https://ncert.nic.in/textbook.php',10) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-7','11111111-1111-1111-1111-111111111111','5','Mathematics','Shapes and Angles — Notes','notes','Identify and compare acute, right and obtuse angles.','https://ncert.nic.in/textbook.php',8) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-8','11111111-1111-1111-1111-111111111111','5','EVS','Every Drop Counts — Notes','notes','Sources of water, scarcity and rainwater harvesting.','https://ncert.nic.in/textbook.php',9) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-9','11111111-1111-1111-1111-111111111111','7','Science','Nutrition in Plants — Notes','notes','Photosynthesis, autotrophs, heterotrophs and parasitic plants.','https://ncert.nic.in/textbook.php',11) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-10','11111111-1111-1111-1111-111111111111','7','Mathematics','Integers — Notes','notes','Properties of integers, multiplication and division rules.','https://ncert.nic.in/textbook.php',10) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-11','11111111-1111-1111-1111-111111111111','8','Science','Force and Pressure — Notes','notes','Contact and non-contact forces, pressure and atmospheric pressure.','https://ncert.nic.in/textbook.php',12) on conflict (id) do nothing;
insert into study_materials (id,school_id,grade,subject,title,type,description,url,minutes) values ('mat-12','11111111-1111-1111-1111-111111111111','8','Mathematics','Rational Numbers — Notes','notes','Closure, commutativity, and representation on the number line.','https://ncert.nic.in/textbook.php',10) on conflict (id) do nothing;
insert into quizzes (id,school_id,grade,subject,title,description,difficulty,duration_sec,question_count,total_marks) values ('quiz-sci6-food','11111111-1111-1111-1111-111111111111','6','Science','Components of Food','Nutrients, balanced diet and deficiency diseases.','easy',300,5,5) on conflict (id) do nothing;
insert into quizzes (id,school_id,grade,subject,title,description,difficulty,duration_sec,question_count,total_marks) values ('quiz-math6-int','11111111-1111-1111-1111-111111111111','6','Mathematics','Integers','Positive & negative numbers on the number line.','easy',300,5,5) on conflict (id) do nothing;
insert into quizzes (id,school_id,grade,subject,title,description,difficulty,duration_sec,question_count,total_marks) values ('quiz-sci6-light','11111111-1111-1111-1111-111111111111','6','Science','Light, Shadows & Reflections','Luminous objects, shadows and mirrors.','medium',300,5,5) on conflict (id) do nothing;
insert into quizzes (id,school_id,grade,subject,title,description,difficulty,duration_sec,question_count,total_marks) values ('quiz-math5-angles','11111111-1111-1111-1111-111111111111','5','Mathematics','Shapes and Angles','Identify and compare angles.','easy',240,5,5) on conflict (id) do nothing;
insert into quizzes (id,school_id,grade,subject,title,description,difficulty,duration_sec,question_count,total_marks) values ('quiz-sci7-nutrition','11111111-1111-1111-1111-111111111111','7','Science','Nutrition in Plants','Photosynthesis and modes of nutrition.','medium',300,5,5) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-food-q1','quiz-sci6-food',1,'Which nutrient is the main source of energy for our body?',ARRAY['Proteins','Carbohydrates','Vitamins','Water']::text[],1,'Carbohydrates are the body’s primary energy source.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-food-q2','quiz-sci6-food',2,'Scurvy is caused by the deficiency of which vitamin?',ARRAY['Vitamin A','Vitamin C','Vitamin D','Vitamin K']::text[],1,'Vitamin C deficiency causes scurvy (bleeding gums).',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-food-q3','quiz-sci6-food',3,'Which of these is a body-building food (rich in protein)?',ARRAY['Rice','Butter','Pulses','Sugar']::text[],2,'Pulses (dals), eggs and milk are rich in proteins.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-food-q4','quiz-sci6-food',4,'The roughage in our food is provided mainly by:',ARRAY['Fats','Minerals','Dietary fibre','Proteins']::text[],2,'Roughage/dietary fibre helps the body get rid of undigested food.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-food-q5','quiz-sci6-food',5,'A diet that has all nutrients in the right amount is called a:',ARRAY['Junk diet','Balanced diet','Liquid diet','Protein diet']::text[],1,'A balanced diet contains all nutrients in adequate quantity.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math6-int-q1','quiz-math6-int',1,'The additive inverse of −7 is:',ARRAY['7','−7','0','1/7']::text[],0,'The additive inverse of −7 is +7 because −7 + 7 = 0.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math6-int-q2','quiz-math6-int',2,'(−3) + (+5) = ?',ARRAY['−8','8','2','−2']::text[],2,'Moving 5 steps right from −3 lands on +2.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math6-int-q3','quiz-math6-int',3,'Which integer is greater: −10 or −3?',ARRAY['−10','−3','Both equal','Cannot say']::text[],1,'On the number line −3 is to the right of −10, so −3 is greater.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math6-int-q4','quiz-math6-int',4,'The sum of an integer and its additive inverse is always:',ARRAY['1','0','The integer itself','Negative']::text[],1,'e.g. 9 + (−9) = 0.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math6-int-q5','quiz-math6-int',5,'(−6) − (−4) = ?',ARRAY['−10','−2','2','10']::text[],1,'Subtracting −4 is adding +4: −6 + 4 = −2.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-light-q1','quiz-sci6-light',1,'An object that gives out its own light is called:',ARRAY['Opaque','Luminous','Transparent','Translucent']::text[],1,'The Sun and a bulb are luminous; they emit their own light.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-light-q2','quiz-sci6-light',2,'A shadow is always formed on the side:',ARRAY['Facing the light','Opposite to the light','Above the object','Around the object']::text[],1,'Light travels in straight lines, so the shadow falls opposite the source.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-light-q3','quiz-sci6-light',3,'Which material is transparent?',ARRAY['Wood','Clear glass','Cardboard','A metal sheet']::text[],1,'Light passes fully through transparent materials like clear glass.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-light-q4','quiz-sci6-light',4,'A pinhole camera forms an image that is:',ARRAY['Upright','Inverted','Coloured only','Invisible']::text[],1,'Because light rays cross at the pinhole, the image is inverted.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci6-light-q5','quiz-sci6-light',5,'The image formed by a plane mirror is:',ARRAY['Real','Virtual and erect','Inverted','Bigger']::text[],1,'A plane mirror forms a virtual, erect image of the same size.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math5-angles-q1','quiz-math5-angles',1,'An angle less than 90° is called:',ARRAY['Right angle','Acute angle','Obtuse angle','Straight angle']::text[],1,'Acute angles are smaller than a right angle (90°).',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math5-angles-q2','quiz-math5-angles',2,'A right angle measures exactly:',ARRAY['45°','90°','180°','360°']::text[],1,'A right angle is 90°.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math5-angles-q3','quiz-math5-angles',3,'A straight angle measures:',ARRAY['90°','180°','270°','360°']::text[],1,'A straight line makes an angle of 180°.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math5-angles-q4','quiz-math5-angles',4,'An angle greater than 90° but less than 180° is:',ARRAY['Acute','Obtuse','Right','Reflex']::text[],1,'Obtuse angles are between 90° and 180°.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-math5-angles-q5','quiz-math5-angles',5,'How many right angles are there in one full turn?',ARRAY['2','3','4','6']::text[],2,'A full turn is 360° = four right angles.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci7-nutrition-q1','quiz-sci7-nutrition',1,'The process by which green plants make their own food is called:',ARRAY['Respiration','Photosynthesis','Digestion','Transpiration']::text[],1,'Photosynthesis uses sunlight, water and CO₂ to make food.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci7-nutrition-q2','quiz-sci7-nutrition',2,'The green pigment that traps sunlight is:',ARRAY['Haemoglobin','Chlorophyll','Melanin','Carotene']::text[],1,'Chlorophyll in leaves captures light energy.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci7-nutrition-q3','quiz-sci7-nutrition',3,'Plants that trap and eat insects (like the pitcher plant) are:',ARRAY['Parasites','Saprotrophs','Insectivorous','Autotrophs']::text[],2,'Insectivorous plants get nitrogen by trapping insects.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci7-nutrition-q4','quiz-sci7-nutrition',4,'Which gas is taken in by plants during photosynthesis?',ARRAY['Oxygen','Nitrogen','Carbon dioxide','Hydrogen']::text[],2,'Plants absorb CO₂ and release O₂ during photosynthesis.',1) on conflict (id) do nothing;
insert into quiz_questions (id,quiz_id,seq,prompt,options,correct_index,explanation,marks) values ('quiz-sci7-nutrition-q5','quiz-sci7-nutrition',5,'Cuscuta (amarbel) is an example of a:',ARRAY['Autotroph','Parasite','Insectivore','Saprotroph']::text[],1,'Cuscuta is a parasitic plant that takes food from its host.',1) on conflict (id) do nothing;
